[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]
# to list all chips, run `probe-rs chip list`
# to list specific chips run `probe-rs chip list | grep -i stm32<xxyy>`
runner = "probe-rs run --chip STM32L432KC"

[build]
# For selecting the target we can use 2 sources:
# 1) https://docs.rust-embedded.org/book/intro/install.html
# 2) https://doc.rust-lang.org/nightly/rustc/platform-support.html
target = "thumbv7em-none-eabihf"

# For attaching usb st-link to wsl: https://learn.microsoft.com/en-us/windows/wsl/connect-usb
# usbipd attach --wsl --busid 2-6

# Logging Tip: Enabling a logging level also enables higher severity logging levels.
[env]
DEFMT_LOG = 'trace'
